name: Workflows

on: [push]

jobs:
  test:
    name: "Testing code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testing with Django
        run: |
          python manage.py test
  build:
    name: "Build code"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Testing with Django
        run: |
          env
